<?php
/** @var Magento\Framework\View\TemplateEngine\Php $this */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Training\Seller\Helper\Url $helper */

$helper = $block->getData('url_helper');
$url = $helper->getSellersUrl();
//$url = $block->getData('sellers_url');
?>
<div style="
    border: solid 2px <?php echo $block->escapeHtmlAttr($block->getData('border_color')); ?>;
    background-color: <?php echo $block->escapeHtmlAttr($block->getData('background_color')); ?>;
    padding: 5px;
    margin: 5px;
    border-radius: 5px;">
     <a href="<?php /* @escapeNotVerified */ echo $url;?>">
         <?php /* @escapeNotVerified */ echo __('Sellers List'); ?>
     </a>
</div>
